services:
  web:
    build: .
    depends_on:
      - bddsql
    container_name: Quanticode1
    ports:
      - "8087:80"
    volumes:
      - .:/var/www/html
    environment: 
      - ALLOW_OVERRIDE=true
      - DB_HOST=bddsql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=quanticode
    restart: always
    
  bddsql:
    image: mariadb
    ports:
      - "3307:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - ALLOW_OVERRIDE=true
      - DB_HOST=bddsql
      - DB_USER=root
      - DB_PASSWORD=root
      - MARIADB_DATABASE=quanticode
      # - DB_NAME=quanticode
    container_name: serverMaria
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8093:80"
    container_name: serverPHPMyAdmin2025
    restart: unless-stopped
    depends_on:
      - bddsql
    environment:
      PMA_HOST: bddsql
      PMA_USER: root
      PMA_PASSWORD: root